baseurl: /teaching

plugins: 
    - jekyll-pandoc

markdown: Pandoc

pandoc:
    extensions:
        - mathjax

defaults:
  - scope:
        path: ""
    values:
        layout: default
        
exclude:
    - LICENSE
    - README.md
    - pull.sh
    - push.sh
